spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/customers/**
        - id: product-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/products/**
        - id: product-service-price
          uri: http://localhost:8060
          predicates:
          - Path=/api/priceHistory/**


server:
  port: 8222
