spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - name: RequestRateLimiter
              args:
                rateLimiter.replenishRate: 5
                rateLimiter.burstCapacity: 5
                rateLimiter.requestedTokens: 1

server:
  port: 8222
